# Site settings
title: গ্রন্থালাপ
email: gronthalap@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  গ্রন্থালাপ ডট কম  বই ডকুমেন্টেশনের একটি স্বেচ্ছাসেবী উদ্যোগ। ২০১৭ সালে একটি মধ্যরাত্রির প্রলাপ থেকে
  এই সাইটের সূচনা। সবাইকে নিয়ে আমরা এগিয়ে যাবো এটাই আমাদের প্রত্যাশা।
logo_location: "https://placeholdit.imgix.net/~text?txtsize=30&bg=F8F8F8&txtclr=002E62&txt=LOGO&w=100&h=100"
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://gronthalap.com" # the base hostname & protocol for your site
#permalink: /:title.html
#gems:
#  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--আরো পড়ুন-->

#show the jumbotron header on index page
show_blog_header: true
